### ISSUE TITLE
API request fails with Community Build v25.5.0.10742

### ISSUE THREAD

**Issue by pierreldff** [cnescatlab/sonar-cnes-report#448]
#### Describe the bug

When I launch a request with following syntax
curl -I -H "Authorization: Basic %Id_token%" "http://mysonarqube.local/api/cnesreport/report?key=myproject&author=Author&token=%generatedToken%"

I got following result

`<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html>`

#### To reproduce
Generate reports with API

#### Expected behavior

Zip archive like manual way does

#### Screenshots & log

On sonarqube logs I got this message

2025.05.21 14:43:29 ERROR web[][o.s.s.p.w.RootFilter] Processing of request /api/cnesreport/report?key=myproject&author=Author&token=%generatedToken% failed
jakarta.servlet.ServletException: Filter execution threw an exception
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:171)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:83)
Caused by: java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite, int)'

#### User environment 
* OS : Debian
* SonarQube version : Community Build v25.5.0.10742
* CNES report plugin version : 5.0.2

**Comment by pierreldff** [comment]
Not a bug.
In fact when we update from 9.9.8 a new parameter is needed (branch) also this route require user token (not project nor global)
